switch:
  - platform: mqtt
    name: "Dog Fed"
    command_topic: "dog_listen/fed"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Dog Medicated"
    command_topic: "dog_listen/med"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Dog Walked"
    command_topic: "dog_listen/walk"
    payload_on: "1"
    payload_off: "0"
  - platform: template